### ISSUE TITLE
How to get truck location when originating tweet is not from the correct lat/long.

### ISSUE THREAD

**Issue by MikeMuxika** [Team-Rocket-Coding-Collective/FoodTruckHeroAPI#9]
For context, here's the conversation that Syed and I had in the google doc.

Syed: 
> I feel like we should always favor the location set in the app vs twitter"
> Or maybe only for the day. If they set their location on a tuesday but tweet on wednesday that they're elsewhere then it should be overriden. However if they tweet their location and our app has the wrong area or it's too general they might want to pin exactly where they are. e.g. they tweet McPherson square but it puts them at a far edge of the park, and they want a more exact location.
> 

Michael:

> Agreed. I actually just created an issue for that before seeing your comment here.  If we favor it setting location in app, we'll also need to take a closer look at how that impact's the suggestion @KatSDC had on users reporting new trucks.

**Comment by psilospore** [comment]
We are planning on updating locations in 3 ways:

- Twitter
    - Could be generic or incorrect e.g. they might say a large park
- User reports location
     - We have to worry about malicious users
- Foodtruck owner reports location
    - Thinking about it we probably need a way for foodtruck owner's to verify they own a truck

The question is when should we prefer one location report over the others.

If on the same day and we have reports from all sources: I would say the preference would be Foodtruck owner, multiple user reports, twitter, less than 3 user reports
